### PR TITLE
Add baseline structure to the CSS

### PR DESCRIPTION
**Pull request by rreusser**
Trying not to be too heavy-handed, but there's an effective and a not effective way to write maintainable CSS, so I've tried to steer things in the right direction.

Inspired by:

See: https://github.com/styleguide/css

### CODE REVIEW

**Comment by bschippers718** [comment]
All inline?

**Comment by rreusser** [comment]
Inline? It's separated into files to encourage thinking about CSS as stylesheets with rules and logic instead of just a font menu with which you style every element independently. Really it's mostly just empty files with comments.

**Comment by bschippers718** [comment]
I'm just being a smart ass, sorry..

I like maintainable CSS too.

**Comment by rreusser** [comment]
(assumed so :) )

**Pull request merged**
