### PR TITLE
Added form factor and OS type during sign in

### PR DESCRIPTION
**Pull request by pavanagrawal**

### CODE REVIEW

**Comment by rreusser** [comment]
Thanks, Pavan! Sidebar question: This is user token api endpoints for mobile users, right? Would this also work for something like the ionic framework? That could be useful to get that stuff linked up…

**Comment by pavanagrawal** [comment]
Hey Ricky,

This will now accept form_factor as "smartphone tablet10 tablet7 desktop"
and os "ios android bb wp7"

We can add more variant as per the requirement.

Does it answer your question?


On Tue, Feb 24, 2015 at 8:43 PM, Ricky Reusser <notifications@github.com>
wrote:

> Thanks, Pavan! Sidebar question: This is user token api endpoints for
> mobile users, right? Would this also work for something like the ionic
> framework? That could be useful to get that stuff linked up…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HappyFunCorp/happy_seed/pull/35#issuecomment-75774191>
> .
>



-- 
Regards,
Pavan Agrawal

**Comment by rreusser** [comment]
I guess it was more a question of whether this approach is relevant for hybrid apps, but no need to focus on that now. We'll figure that out when needed. Thanks!

**Comment by pavanagrawal** [comment]
Yes the app is for hibrid app, these attributes are bind with use tokens and that is geta generated for every other divice.

**Pull request merged**
